### ISSUE TITLE
Regular zombie explodes in death without setting the explosions on death.

### ISSUE THREAD

**Issue by ZERORobot000** [supersonic1999/ZombieInvasion#16]
The saturday I got the issue of regular zombies exploding always, just the normal zombie, the others doesn't and it doesn't have set to explode upon death.

I need help how to solve this if an addon cause this or a bug of the addon.

**Comment by supersonic1999** [comment]
Hi, I just booted up gmod and checked it out. cant seem to replicate the issue.

Can you post a screenshot ingame with the zinv menu open?

cheers
