### ISSUE TITLE
ZINV Options tab not appearing

### ISSUE THREAD

**Issue by FuckGitHubNotLettingMeSignInMainAccount** [supersonic1999/ZombieInvasion#17]
For some reason the ZINV tab won't pop up in Options tab at all. I've used this mod many times before but it's not working on my server or in single player. Unsure of why this is happening. It would be fine if there was some type of command to open up the menu where I can edit NPC spawn chances and etc. and as well having commands to change npc max limit (there may be one, but it isn't in the description) although there are commands for the max distance, min distance, and whether the mod is on or off. Any help would be nice (even if you can't fix or figure out why the tab is not popping up in options, it would be nice if there were commands to open everything up for people who have mental disabilities such as myself.

![zinv](https://user-images.githubusercontent.com/84546884/119057909-33bf6380-b982-11eb-9d9c-cf4ea08fb86e.png)

**Comment by FuckGitHubNotLettingMeSignInMainAccount** [comment]
Also accidently pasted the wrong title link, lmfao. Don't actually think your mod sucks, actually really good. Any help would be great, if you could change the name to "ZINV tab not in options" that would be great as well if it is possible

**Comment by FuckGitHubNotLettingMeSignInMainAccount** [comment]
Accidently copied the wrong thing when talking about something else as the title and didn't check. Don't actually think your mod sucks, it's actually really good. Any help would be greatly appreciated

**Comment by supersonic1999** [comment]
Sorry i didnt reply, didnt notice your message. 

Problem is usually conflicts with other mods, try disabling them and enable them back one by one.
