### ISSUE TITLE
Idea: Create Presets

### ISSUE THREAD

**Issue by Zoidberg656** [supersonic1999/ZombieInvasion#19]
I love this mod and use it constantly to just play zombie survival in single player. Hours of fun.
But sometimes the tedious nature of setting up a different list of NPCs and weapons is far from enjoyable.

If it's possible to create presets with names to then select later on so you don't need to completely re-add each and every setting like you once had it, that would be awesome! Because I do enjoy the variety of fighting zombies one day and a large list of combine the next, but it would make things so much faster and efficient.

Thank you.

**Comment by supersonic1999** [comment]
Hi,

You can do this by setting the max spawn on each of your presets to 0 to disable that one for use later.

Might be worth adding an enabled/disabled button for each for better understanding.
