### ISSUE TITLE
Doesn't seem to work on dedicated server.

### ISSUE THREAD

**Issue by bananaDevMan** [supersonic1999/ZombieInvasion#20]
Seems like a gmod update broke this or something? My gmod server is running the beta branch and it used to work fine but now it is calling errors on the client?

Error: https://pastebin.com/qWT77Xqw

**Comment by supersonic1999** [comment]
will look into it now!

**Comment by supersonic1999** [comment]
Seems to be all working fine.
I also see in the log you are also running zinv++ which is a modified version of my original one.

Mine has been updated recently with much more features and bug fixes.

https://steamcommunity.com/sharedfiles/filedetails/?id=597017711&searchtext=zinv

**Comment by bananaDevMan** [comment]
Hey man sorry for not getting to you in a while. But this was your addon, I slightly modified it so npcs spawned outside of where the player can see. I've also tried your vanilla addon and it did not work aswell.
