### ISSUE TITLE
Idea: Constant movement

### ISSUE THREAD

**Issue by WheelAxle** [supersonic1999/ZombieInvasion#21]
So I've just found this mod, and it's pretty great. I've played around a lot on arena maps in a deathmatch gamemode. I would love it if there was an option for npcs to not stay idle at a position and constantly move from node to node. Make the map feel more alive, and I wouldn't have to chase after them all the time?

I also don't mean the "chase" feature in the mod already. I have other npcs spawned in that would make it better for them to fight aswell.

I'm not a programmer, so I don't know how difficult to implement this is. Thanks for reading if you made it this far.

**Comment by supersonic1999** [comment]
Hi, 

This is already in the mod. change the 'chaser?' option to roamer to allow them to randomly move around the map
