### ISSUE TITLE
add NPC Hard Cap 

### ISSUE THREAD

**Issue by Wanaskiwin** [supersonic1999/ZombieInvasion#8]
With the way ZINV was before we had it set up so all NPCs had a chance to spawn, now it seems to just try and spawn everything at once, which makes this a lot less usable to have it occasionally spawn things like random objects or very very strong NPCs, I think its prudent to have spawn chances for this sort of thing, it seems to be attempting to just spawn every type of NPC atleast once and we have like maybe 100 or so NPCs ranging from combine to Vindictus bosses, we dont want Vindictus bosses to just out right spawn, we want them to have a percent chance to spawn

 I'd like to see the NPC Hard cap reintroduced or atleast a way to make Zinv Prioritize npcs over other npcs

**Comment by supersonic1999** [comment]
Ah yea i was thinking that the other day after i updated, i accidentally borked the chance mechanic, ill get that sorted for next patch!
